apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: my-ns
  labels:
    app: wordpress
spec:
    type: NodePort
    selector:
      app: wordpress
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
# this is a dummy service that simulate service locally
apiVersion: v1
kind: Service
metadata:
  name: wordpress-db-service
  namespace: my-ns
  labels:
    db: wordpress
spec:
    clusterIP: None
    selector:
      db: wordpress
    ports:
      - protocol: TCP
        port: 3306
        targetPort: 3306